import { forwardRef, useEffect, useImperativeHandle, useMemo, useRef, useState } from 'react'
import type { CSSProperties, MouseEvent, ReactNode } from 'react'
import type { Bug, BugSeverity, DesktopApi, ExportProgress, GitLabProject, GitLabPublishMode, GitLabPublishSettings, GooglePublishSettings, MentionIdentity, PublishTarget, SeveritySettings, SlackChannel, SlackMentionUser, SlackPublishSettings, SlackThreadMode } from '@shared/types'
import { localFileUrl } from '@/lib/api'
import { useI18n } from '@/lib/i18n'

interface Props {
  api: DesktopApi
  sessionId: string
  bugs: Bug[]
  selectedBugId: string | null
  onSelect(bug: Bug): void
  onMutated(): void
  allowExport?: boolean
  autoFocusLatest?: boolean
  buildVersion?: string
  tester?: string
  testNote?: string
  hasSessionMicTrack?: boolean
  markerToolbar?: ReactNode
}

export interface BugListHandle {
  exportAll(): void
  exporting: boolean
}

function fmt(ms: number): string {
  const s = Math.floor(ms / 1000), m = Math.floor(s / 60), r = s % 60
  return `${m}:${r.toString().padStart(2, '0')}`
}

const BASE_SEVERITIES: BugSeverity[] = ['note', 'major', 'normal', 'minor', 'improvement']
const CLIP_MIN_SEC = 0
const CLIP_MAX_SEC = 60
const THUMB_PENDING_MS = 45_000
const LOGCAT_COLLAPSED_LINES = 2
const LOGCAT_EXPANDED_LINES = 10
const ORIGINAL_FILES_WARNING_KEY = 'loupe.skipOriginalFilesWarning'

const DEFAULT_SEVERITIES: SeveritySettings = {
  note: { label: 'default', color: '#a1a1aa' },
  major: { label: 'Critical', color: '#ff4d4f' },
  normal: { label: 'Bug', color: '#f59e0b' },
  minor: { label: 'Polish', color: '#22b8f0' },
  improvement: { label: 'Note', color: '#22c55e' },
  custom1: { label: '', color: '#8b5cf6' },
  custom2: { label: '', color: '#ec4899' },
  custom3: { label: '', color: '#14b8a6' },
  custom4: { label: '', color: '#eab308' },
}

const AUDIO_TRIGGER_WORDS = [
  '記錄一下', '记录一下', '紀錄一下', '註記一下', '注记一下',
  '幫我記錄', '帮我记录', '幫我紀錄', '幫我註記', '帮我注记',
  'mark this', 'record this', 'note this', 'add marker',
  '記錄', '记录', '紀錄', '註記', '注记', '標記', '标记',
  'mark', 'record', 'note',
].sort((a, b) => b.length - a.length)

function visibleSeverities(severities: SeveritySettings): BugSeverity[] {
  const customSeverities = Object.keys(severities)
    .filter(severity => !BASE_SEVERITIES.includes(severity) && severities[severity]?.label?.trim())
    .sort((a, b) => {
      const aNum = Number(a.match(/^custom(\d+)$/)?.[1] ?? Number.MAX_SAFE_INTEGER)
      const bNum = Number(b.match(/^custom(\d+)$/)?.[1] ?? Number.MAX_SAFE_INTEGER)
      return aNum === bNum ? a.localeCompare(b) : aNum - bNum
    })
  return [
    ...BASE_SEVERITIES,
    ...customSeverities,
  ]
}

function severityLabel(severities: SeveritySettings, severity: BugSeverity): string {
  return severities[severity]?.label?.trim() || DEFAULT_SEVERITIES[severity]?.label || severity
}

function severityColor(severities: SeveritySettings, severity: BugSeverity): string {
  return severities[severity]?.color || DEFAULT_SEVERITIES[severity]?.color || '#a1a1aa'
}

function markerSourceHint(bug: Bug): string {
  return bug.source === 'audio-auto'
    ? 'Generated by audio analysis. It will be replaced when audio is re-analyzed, even if edited.'
    : 'Created manually. Audio re-analysis keeps this marker.'
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function highlightAudioTriggers(text: string): Array<string | JSX.Element> {
  if (!text) return []
  const pattern = new RegExp(`(${AUDIO_TRIGGER_WORDS.map(escapeRegExp).join('|')})`, 'gi')
  const parts = text.split(pattern)
  return parts.map((part, index) => {
    if (!part) return part
    const isTrigger = AUDIO_TRIGGER_WORDS.some(word => word.toLowerCase() === part.toLowerCase())
    return isTrigger
      ? <span key={index} className="rounded bg-red-500/20 px-0.5 font-semibold text-red-300">{part}</span>
      : part
  })
}

function slackUserLabel(user: SlackMentionUser): string {
  return user.displayName || user.realName || user.name || user.id
}

function mentionIdentityLabel(identity: MentionIdentity): string {
  return identity.displayName || identity.email || identity.googleEmail || identity.gitlabUsername || identity.slackUserId || identity.id
}

function MentionProviderBadges({ hasSlack, hasGitLab, hasGoogle }: { hasSlack: boolean; hasGitLab: boolean; hasGoogle: boolean }) {
  if (!hasSlack && !hasGitLab && !hasGoogle) {
    return (
      <span className="rounded-full border border-zinc-800 bg-zinc-900 px-1.5 py-0.5 text-[10px] font-medium text-zinc-500">
        No mappings
      </span>
    )
  }
  return (
    <>
      {hasSlack && (
        <span className="rounded-full border border-sky-900/70 bg-sky-950/50 px-1.5 py-0.5 text-[10px] font-medium text-sky-300">
          Slack
        </span>
      )}
      {hasGitLab && (
        <span className="rounded-full border border-orange-900/70 bg-orange-950/50 px-1.5 py-0.5 text-[10px] font-medium text-orange-300">
          GitLab
        </span>
      )}
      {hasGoogle && (
        <span className="rounded-full border border-emerald-900/70 bg-emerald-950/50 px-1.5 py-0.5 text-[10px] font-medium text-emerald-300">
          Google
        </span>
      )}
    </>
  )
}

function slackChannelLabel(channel: SlackChannel): string {
  return `${channel.isPrivate ? 'private / ' : '#'}${channel.name}${channel.isMember === false ? ' (not joined)' : ''}`
}

function slackPublishToken(settings: SlackPublishSettings | null): string {
  if (!settings) return ''
  const userToken = settings.userToken?.trim() ?? ''
  const botToken = settings.botToken.trim()
  return settings.publishIdentity === 'bot' ? botToken : userToken || botToken
}

function isSlackConnected(settings: SlackPublishSettings | null): boolean {
  return Boolean(slackPublishToken(settings))
}

function isGitLabConnected(settings: GitLabPublishSettings | null): boolean {
  return Boolean(settings?.token?.trim() && settings?.baseUrl?.trim())
}

function isGoogleDriveConnected(settings: GooglePublishSettings | null): boolean {
  return Boolean((settings?.token?.trim() || settings?.refreshToken?.trim()) && settings?.driveFolderId?.trim())
}

function normalizeManualSlackMentions(value: string): string[] {
  return Array.from(new Set(value
    .split(/[\s,;]+/)
    .map(part => part.trim())
    .map(part => part.replace(/^<!(subteam\^[^>|]+)(?:\|[^>]+)?>$/, '!$1'))
    .map(part => part.replace(/^<!(here|channel|everyone)>$/, '!$1'))
    .map(part => part.replace(/^@(here|channel|everyone)$/, '!$1'))
    .filter(part => part.startsWith('!'))))
}

function formatManualSlackMentions(ids: string[]): string {
  return ids.filter(id => id.startsWith('!')).map(id => id.replace(/^!(here|channel|everyone)$/, '@$1')).join(', ')
}

function channelIdFromSettings(slack: Awaited<ReturnType<DesktopApi['settings']['get']>>['slack']): string {
  const channels = (slack.channels ?? []).filter(channel => !channel.isArchived)
  return channels.some(channel => channel.id === slack.channelId) ? slack.channelId : ''
}

function withTimeout<T>(promise: Promise<T>, ms: number, message: string): Promise<T> {
  return new Promise((resolve, reject) => {
    const timer = window.setTimeout(() => reject(new Error(message)), ms)
    promise.then(
      value => {
        window.clearTimeout(timer)
        resolve(value)
      },
      error => {
        window.clearTimeout(timer)
        reject(error)
      },
    )
  })
}

function latestLogcatLines(logcat: string, lineCount: number): string {
  return logcat.split(/\r?\n/).slice(-lineCount).join('\n')
}

function DownloadIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M12 3v12" />
      <path d="m7 10 5 5 5-5" />
      <path d="M5 21h14" />
    </svg>
  )
}

function DeleteIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}

function MicIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M12 3a3 3 0 0 0-3 3v6a3 3 0 0 0 6 0V6a3 3 0 0 0-3-3Z" />
      <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
      <path d="M12 19v3" />
    </svg>
  )
}

function ThumbnailWaiting({ label }: { label: string }) {
  return (
    <div className="flex h-24 w-28 items-center justify-center rounded border border-zinc-800 bg-zinc-950">
      <div
        className="h-5 w-5 animate-spin rounded-full border-2 border-zinc-700 border-t-blue-400"
        aria-label={label}
        title={label}
      />
    </div>
  )
}

function blobToBase64(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = () => resolve(String(reader.result).split(',')[1] ?? '')
    reader.onerror = () => reject(reader.error)
    reader.readAsDataURL(blob)
  })
}

function notifyExported(api: DesktopApi, firstPath: string, count: number, t: (key: string, params?: Record<string, string | number>) => string): void {
  const message = count === 1
    ? t('export.done.one', { path: firstPath })
    : t('export.done.many', { count })
  if (askConfirm(message)) {
    void api.app.openPath(exportRootFromOutputPath(firstPath))
  }
}

function notifyFullRecordingExported(api: DesktopApi, firstPath: string, t: (key: string, params?: Record<string, string | number>) => string): void {
  const recordsPath = containingFolderFromOutputPath(firstPath)
  if (askConfirm(t('export.done.noMarkers', { path: recordsPath }))) {
    void api.app.openPath(recordsPath)
  }
}

function askConfirm(message: string): boolean {
  return typeof window.confirm === 'function' ? window.confirm(message) : true
}

function containingFolderFromOutputPath(filePath: string): string {
  const parts = filePath.split(/[\\/]/)
  return parts.slice(0, -1).join(filePath.includes('\\') ? '\\' : '/') || filePath
}

function exportRootFromOutputPath(filePath: string): string {
  const parts = filePath.split(/[\\/]/)
  const parent = parts.at(-2)?.toLowerCase()
  if ((parent === 'records' || parent === 'report') && parts.length > 2) {
    return parts.slice(0, -2).join(filePath.includes('\\') ? '\\' : '/')
  }
  return parts.slice(0, -1).join(filePath.includes('\\') ? '\\' : '/') || filePath
}

interface ExportRequest {
  bugs: Bug[]
  bugIds: string[]
}

interface ExportConfirmDialogProps {
  count: number
  outputRoot: string
  reportTitle: string
  buildVersion: string
  tester: string
  testNote: string
  includeLogcat: boolean
  includeMicTrack: boolean
  includeOriginalFiles: boolean
  mergeOriginalAudio: boolean
  hasSessionMicTrack: boolean
  hasMarkerAudioNotes: boolean
  slackConnected: boolean
  gitlabConnected: boolean
  googleDriveConnected: boolean
  slackConnecting: boolean
  publishSlack: boolean
  publishGitLab: boolean
  publishGoogleDrive: boolean
  slackThreadMode: SlackThreadMode
  slackChannels: SlackChannel[]
  slackChannelId: string
  mentionOptions: MentionOption[]
  slackMentionIds: string[]
  slackMentionAliases: Record<string, string>
  slackManualMentionInput: string
  slackDirectoryRefreshing: boolean
  slackDirectoryError: string
  gitlabMode: GitLabPublishMode
  gitlabProjectId: string
  gitlabProjects: GitLabProject[]
  gitlabProjectsRefreshing: boolean
  gitlabProjectsError: string
  busy: boolean
  error: string
  canceling: boolean
  progress: ExportProgress | null
  hasMissingNotes: boolean
  onOutputRootChange(value: string): void
  onReportTitleChange(value: string): void
  onBuildVersionChange(value: string): void
  onTesterChange(value: string): void
  onTestNoteChange(value: string): void
  onIncludeLogcatChange(value: boolean): void
  onIncludeMicTrackChange(value: boolean): void
  onIncludeOriginalFilesChange(value: boolean): void
  onMergeOriginalAudioChange(value: boolean): void
  onConnectSlack(): void
  onPublishSlackChange(value: boolean): void
  onPublishGitLabChange(value: boolean): void
  onPublishGoogleDriveChange(value: boolean): void
  onSlackThreadModeChange(value: SlackThreadMode): void
  onSlackChannelIdChange(value: string): void
  onSlackMentionIdsChange(value: string[]): void
  onSlackManualMentionInputChange(value: string): void
  onRefreshSlackDirectory(): void
  onGitLabModeChange(value: GitLabPublishMode): void
  onGitLabProjectIdChange(value: string): void
  onRefreshGitLabProjects(): void
  onBrowseOutputRoot(): void
  onCancel(): void
  onConfirm(): void
}

function ExportConfirmDialog({
  count,
  outputRoot,
  reportTitle,
  buildVersion,
  tester,
  testNote,
  includeLogcat,
  includeMicTrack,
  includeOriginalFiles,
  mergeOriginalAudio,
  hasSessionMicTrack,
  hasMarkerAudioNotes,
  slackConnected,
  gitlabConnected,
  googleDriveConnected,
  slackConnecting,
  publishSlack,
  publishGitLab,
  publishGoogleDrive,
  slackThreadMode,
  slackChannels,
  slackChannelId,
  mentionOptions,
  slackMentionIds,
  slackMentionAliases,
  slackManualMentionInput,
  slackDirectoryRefreshing,
  slackDirectoryError,
  gitlabMode,
  gitlabProjectId,
  gitlabProjects,
  gitlabProjectsRefreshing,
  gitlabProjectsError,
  busy,
  error,
  canceling,
  progress,
  hasMissingNotes,
  onOutputRootChange,
  onReportTitleChange,
  onBuildVersionChange,
  onTesterChange,
  onTestNoteChange,
  onIncludeLogcatChange,
  onIncludeMicTrackChange,
  onIncludeOriginalFilesChange,
  onMergeOriginalAudioChange,
  onConnectSlack,
  onPublishSlackChange,
  onPublishGitLabChange,
  onPublishGoogleDriveChange,
  onSlackThreadModeChange,
  onSlackChannelIdChange,
  onSlackMentionIdsChange,
  onSlackManualMentionInputChange,
  onRefreshSlackDirectory,
  onGitLabModeChange,
  onGitLabProjectIdChange,
  onRefreshGitLabProjects,
  onBrowseOutputRoot,
  onCancel,
  onConfirm,
}: ExportConfirmDialogProps) {
  const isSlack = publishSlack
  const isGitLab = publishGitLab
  const isGoogleDrive = publishGoogleDrive
  const { t } = useI18n()
  const progressPct = progress && progress.total > 0
    ? Math.round((progress.current / progress.total) * 100)
    : 0
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4" data-testid="export-dialog">
      <div className="flex max-h-[calc(100vh-2rem)] w-full max-w-lg flex-col overflow-hidden rounded-lg border border-zinc-700 bg-zinc-900 shadow-2xl">
        <div className="shrink-0 px-4 pt-4">
          <div className="text-sm font-medium text-zinc-100">{count === 0 ? t('export.title.noMarkers') : count === 1 ? t('export.title.one') : t('export.title.many', { count })}</div>
          <div className="mt-1 text-xs text-zinc-500">{t('export.body')}</div>
        </div>

        <div className="min-h-0 flex-1 overflow-y-auto px-4 py-3">
        <label className="mt-4 block text-xs text-zinc-500">
          {t('export.outputFolder')}
          <div className="mt-1 flex gap-2">
            <input
              value={outputRoot}
              onChange={(e) => onOutputRootChange(e.target.value)}
              className="min-w-0 flex-1 rounded bg-zinc-950 px-3 py-2 text-sm text-zinc-200 outline-none focus:ring-1 focus:ring-blue-600"
              autoFocus
            />
            <button
              type="button"
              onClick={onBrowseOutputRoot}
              disabled={busy}
              className="rounded bg-zinc-800 px-3 py-2 text-sm text-zinc-200 hover:bg-zinc-700 disabled:opacity-50"
            >
              {t('common.browse')}
            </button>
          </div>
        </label>

        <label className="mt-3 block text-xs font-semibold text-zinc-300">
          Report title
          <input
            value={reportTitle}
            onChange={(e) => onReportTitleChange(e.target.value)}
            placeholder="Loupe QA Report"
            className="mt-1 w-full rounded bg-zinc-950 px-3 py-2 text-sm font-normal text-zinc-200 outline-none focus:ring-1 focus:ring-blue-600"
          />
        </label>

        <label className="mt-3 block text-xs font-semibold text-zinc-300">
          {t('new.buildVersion')}
          <input
            value={buildVersion}
            onChange={(e) => onBuildVersionChange(e.target.value)}
            placeholder="1.4.2-RC3"
            className="mt-1 w-full rounded bg-zinc-950 px-3 py-2 text-sm font-normal text-zinc-200 outline-none focus:ring-1 focus:ring-blue-600"
          />
        </label>

        <div className="mt-3 grid grid-cols-2 gap-3">
          <label className="text-xs text-zinc-500">
            {t('export.tester')}
            <input
              value={tester}
              onChange={(e) => onTesterChange(e.target.value)}
              placeholder={t('export.qaName')}
              className="mt-1 w-full rounded bg-zinc-950 px-3 py-2 text-sm text-zinc-200 outline-none focus:ring-1 focus:ring-blue-600"
            />
          </label>
          <label className="text-xs text-zinc-500">
            {t('export.testNote')}
            <input
              value={testNote}
              onChange={(e) => onTestNoteChange(e.target.value)}
              placeholder={t('export.scope')}
              className="mt-1 w-full rounded bg-zinc-950 px-3 py-2 text-sm text-zinc-200 outline-none focus:ring-1 focus:ring-blue-600"
            />
          </label>
        </div>

        <label className="mt-3 flex items-center gap-2 text-xs text-zinc-400">
          <input
            type="checkbox"
            checked={includeLogcat}
            onChange={(e) => onIncludeLogcatChange(e.target.checked)}
            className="h-4 w-4 accent-blue-600"
          />
          Export marker logcat as sidecar text files
        </label>

        {hasSessionMicTrack && (
          <label className="mt-3 flex items-start gap-2 text-xs text-zinc-400">
            <input
              type="checkbox"
              checked={includeMicTrack}
              onChange={(e) => onIncludeMicTrackChange(e.target.checked)}
              className="mt-0.5 h-4 w-4 accent-blue-600"
            />
            <span>
              <span className="block text-zinc-300">Use session MIC track in exported clips</span>
              {hasMarkerAudioNotes && (
                <span className="mt-1 block text-amber-300">This replaces marker audio notes for these exports.</span>
              )}
            </span>
          </label>
        )}

        <div className="mt-4 space-y-3">
          <div>
            <div className="text-xs font-medium text-zinc-300">Publish</div>
            <div className="mt-1 text-xs text-zinc-500">Local files are always exported.</div>
          </div>

          <section className={`rounded border p-3 ${isSlack ? 'border-blue-700 bg-blue-950/20' : 'border-zinc-800 bg-zinc-950/60'}`}>
            <div className="flex items-center justify-between gap-3">
              <span>
                <span className="block text-sm font-medium text-zinc-200">Slack</span>
                <span className="mt-1 block text-xs text-zinc-500">Post the summary, detailed PDF, and marker videos to Slack.</span>
              </span>
              {slackConnected ? (
                <label className="flex shrink-0 cursor-pointer items-center gap-2 text-xs text-zinc-300">
                  <span>Publish</span>
                  <input
                    type="checkbox"
                    checked={isSlack}
                    onChange={(e) => onPublishSlackChange(e.target.checked)}
                    className="h-4 w-4 accent-blue-600"
                  />
                </label>
              ) : (
                <button
                  type="button"
                  onClick={onConnectSlack}
                  disabled={busy || slackConnecting}
                  className="shrink-0 rounded bg-emerald-700 px-3 py-2 text-xs font-medium text-white hover:bg-emerald-600 disabled:opacity-50"
                >
                  {slackConnecting ? 'Connecting...' : 'Connect Slack'}
                </button>
              )}
            </div>

            {isSlack && (
              <div className="mt-3 space-y-3 border-t border-blue-900/60 pt-3">
              <div>
                <div className="flex items-center justify-between gap-2">
                  <label className="min-w-0 flex-1 text-xs text-zinc-500">
                    Channel
                    <SlackChannelPicker
                      channels={slackChannels}
                      value={slackChannelId}
                      onChange={onSlackChannelIdChange}
                      disabled={busy}
                      loading={slackDirectoryRefreshing}
                      onOpen={() => {
                        if (slackChannels.length === 0 && !slackDirectoryRefreshing) onRefreshSlackDirectory()
                      }}
                    />
                  </label>
                  <button
                    type="button"
                    onClick={onRefreshSlackDirectory}
                    disabled={busy || slackDirectoryRefreshing}
                    className="mt-5 shrink-0 rounded bg-zinc-800 px-3 py-2 text-xs text-zinc-200 hover:bg-zinc-700 disabled:opacity-50"
                  >
                    {slackDirectoryRefreshing ? 'Refreshing...' : 'Refresh'}
                  </button>
                </div>
                {slackDirectoryError && <div className="mt-1 text-xs text-red-300">{slackDirectoryError}</div>}
                {slackChannels.length === 0 && !slackDirectoryError && (
                  <div className="mt-1 text-xs text-zinc-500">Reconnect Slack after scope changes, then refresh channels.</div>
                )}
              </div>

              <div>
                <div className="text-xs text-zinc-500">Mentions</div>
                <div className="mt-1">
                  <MentionPicker
                    options={mentionOptions}
                    selectedIds={slackMentionIds}
                    aliases={slackMentionAliases}
                    dropdownMode="fixed"
                    onChange={(ids) => {
                      onSlackMentionIdsChange(ids)
                      onSlackManualMentionInputChange(formatManualSlackMentions(ids))
                    }}
                  />
                </div>
              </div>

              <div>
                <div className="text-xs text-zinc-500">Slack thread layout</div>
                <div className="mt-2 grid grid-cols-2 gap-2" role="group" aria-label="Slack publish mode">
                  <button
                    type="button"
                    onClick={() => onSlackThreadModeChange('single-thread')}
                    className={`rounded px-3 py-2 text-sm ${slackThreadMode === 'single-thread' ? 'bg-sky-700 text-white' : 'bg-zinc-800 text-zinc-300 hover:bg-zinc-700'}`}
                  >
                    All markers in one thread
                  </button>
                  <button
                    type="button"
                    onClick={() => onSlackThreadModeChange('per-marker-thread')}
                    className={`rounded px-3 py-2 text-sm ${slackThreadMode === 'per-marker-thread' ? 'bg-sky-700 text-white' : 'bg-zinc-800 text-zinc-300 hover:bg-zinc-700'}`}
                  >
                    Every marker per thread
                  </button>
                </div>
                <div className="mt-2 text-xs text-zinc-500">
                  Marker-level mentions override this default mention list; otherwise these mentions are added to marker replies.
                </div>
              </div>
            </div>
            )}
          </section>

          <section className={`rounded border p-3 ${isGitLab ? 'border-sky-700 bg-sky-950/20' : 'border-zinc-800 bg-zinc-950/60'}`}>
            <div className="flex items-center justify-between gap-3">
              <span>
                <span className="block text-sm font-medium text-zinc-200">GitLab</span>
                <span className="mt-1 block text-xs text-zinc-500">Create GitLab issue output for the selected markers.</span>
              </span>
              {gitlabConnected ? (
                <label className="flex shrink-0 cursor-pointer items-center gap-2 text-xs text-zinc-300">
                  <span>Publish</span>
                  <input
                    type="checkbox"
                    checked={isGitLab}
                    onChange={(e) => onPublishGitLabChange(e.target.checked)}
                    className="h-4 w-4 accent-blue-600"
                  />
                </label>
              ) : (
                <span className="shrink-0 rounded border border-zinc-700 px-3 py-2 text-xs text-zinc-500">????</span>
              )}
            </div>

            {isGitLab && (
              <div className="mt-3 space-y-3 border-t border-sky-900/60 pt-3">
                <div>
                  <div className="flex items-center justify-between gap-2">
                    <label className="min-w-0 flex-1 text-xs text-zinc-500">
                      Project
                      <GitLabProjectPicker
                        projects={gitlabProjects}
                        value={gitlabProjectId}
                        loading={gitlabProjectsRefreshing}
                        onOpen={() => {
                          if (gitlabProjects.length === 0 && !gitlabProjectsRefreshing) onRefreshGitLabProjects()
                        }}
                        onChange={onGitLabProjectIdChange}
                      />
                    </label>
                    <button
                      type="button"
                      onClick={onRefreshGitLabProjects}
                      disabled={busy || gitlabProjectsRefreshing}
                      className="mt-5 shrink-0 rounded bg-zinc-800 px-3 py-2 text-xs text-zinc-200 hover:bg-zinc-700 disabled:opacity-50"
                    >
                      {gitlabProjectsRefreshing ? 'Refreshing...' : 'Refresh'}
                    </button>
                  </div>
                  {gitlabProjectsError && <div className="mt-1 text-xs text-red-300">{gitlabProjectsError}</div>}
                  {gitlabProjects.length === 0 && !gitlabProjectsError && (
                    <div className="mt-1 text-xs text-zinc-500">Refresh projects after setting a GitLab token in Publish settings, or enter group/project manually.</div>
                  )}
                </div>

                <div>
                  <div className="text-xs text-zinc-500">GitLab publish mode</div>
                  <div className="mt-2 grid grid-cols-2 gap-2" role="group" aria-label="GitLab publish mode">
                    <button
                      type="button"
                      onClick={() => onGitLabModeChange('single-issue')}
                      className={`rounded px-3 py-2 text-sm ${gitlabMode === 'single-issue' ? 'bg-sky-700 text-white' : 'bg-zinc-800 text-zinc-300 hover:bg-zinc-700'}`}
                    >
                      Single issue
                    </button>
                    <button
                      type="button"
                      onClick={() => onGitLabModeChange('per-marker-issue')}
                      className={`rounded px-3 py-2 text-sm ${gitlabMode === 'per-marker-issue' ? 'bg-sky-700 text-white' : 'bg-zinc-800 text-zinc-300 hover:bg-zinc-700'}`}
                    >
                      Issue per marker
                    </button>
                  </div>
                </div>
              </div>
            )}
          </section>

          <section className={`rounded border p-3 ${isGoogleDrive ? 'border-emerald-700 bg-emerald-950/20' : 'border-zinc-800 bg-zinc-950/60'}`}>
            <div className="flex items-center justify-between gap-3">
              <span>
                <span className="block text-sm font-medium text-zinc-200">Google Drive</span>
                <span className="mt-1 block text-xs text-zinc-500">Upload the full local export folder to the configured Drive folder and update Google Sheet rows when enabled.</span>
              </span>
              {googleDriveConnected ? (
                <label className="flex shrink-0 cursor-pointer items-center gap-2 text-xs text-zinc-300">
                  <span>Publish</span>
                  <input
                    type="checkbox"
                    checked={isGoogleDrive}
                    onChange={(e) => onPublishGoogleDriveChange(e.target.checked)}
                    className="h-4 w-4 accent-blue-600"
                  />
                </label>
              ) : (
                <span className="shrink-0 rounded border border-zinc-700 px-3 py-2 text-xs text-zinc-500">????</span>
              )}
            </div>
          </section>
        </div>

        {hasMissingNotes && (
          <div className="mt-3 rounded border border-amber-700 bg-amber-950/30 px-3 py-2 text-xs text-amber-200">
            {t('export.missingNotes')}
          </div>
        )}

        {count === 0 && (
          <div className="mt-3 rounded border border-amber-700 bg-amber-950/30 px-3 py-2 text-xs text-amber-200">
            {t('export.noMarkersBody')}
          </div>
        )}

        {busy && (
          <div className="mt-4 rounded border border-zinc-800 bg-zinc-950/70 p-3">
            <div className="flex items-center justify-between gap-3 text-xs text-zinc-400">
              <span>{progress?.message ?? t('export.progressStarting')}</span>
              <span className="font-mono tabular-nums">{progressPct}%</span>
            </div>
            <div className="mt-2 h-2 overflow-hidden rounded-full bg-zinc-800">
              <div
                className="h-full rounded-full bg-blue-500 transition-all duration-200"
                style={{ width: `${progressPct}%` }}
              />
            </div>
            <div className="mt-2 grid grid-cols-2 gap-2 text-[11px] text-zinc-500">
              <div>
                {t('export.progressStep', {
                  current: progress?.current ?? 0,
                  total: progress?.total ?? 0,
                })}
              </div>
              <div className="text-right">
                {t('export.progressRemaining', { count: progress?.remaining ?? count })}
              </div>
            </div>
            {progress?.detail && (
              <div className="mt-2 break-words text-[11px] leading-4 text-zinc-500">{progress.detail}</div>
            )}
          </div>
        )}

        {error && (
          <div className="mt-3 rounded border border-red-800 bg-red-950/40 px-3 py-2 text-xs text-red-200">
            {error}
          </div>
        )}

        <label className="mt-3 flex items-start gap-2 text-xs text-zinc-400">
          <input
            type="checkbox"
            aria-label="輸出全時長錄影"
            data-testid="include-original-files"
            checked={includeOriginalFiles}
            onChange={(e) => {
              onIncludeOriginalFilesChange(e.target.checked)
              if (!e.target.checked) onMergeOriginalAudioChange(false)
            }}
            className="mt-0.5 h-4 w-4 accent-blue-600"
          />
          <span>
            <span className="block text-zinc-300">輸出全時長錄影</span>
            <span className="mt-1 block text-zinc-500">Copies the full-length recording into the local export folder only. This file is not uploaded to Slack or GitLab.</span>
          </span>
        </label>

        {includeOriginalFiles && hasSessionMicTrack && (
          <label className="ml-6 mt-2 flex items-start gap-2 text-xs text-zinc-400">
            <input
              type="checkbox"
              aria-label="合併音軌"
              data-testid="merge-original-audio"
              checked={mergeOriginalAudio}
              onChange={(e) => onMergeOriginalAudioChange(e.target.checked)}
              className="mt-0.5 h-4 w-4 accent-blue-600"
            />
            <span>
              <span className="block text-zinc-300">合併音軌</span>
              <span className="mt-1 block text-zinc-500">MIC audio is mixed over the original video audio; it does not replace the original track.</span>
            </span>
          </label>
        )}
        </div>

        <div className="shrink-0 border-t border-zinc-800 bg-zinc-900 px-4 py-3">
          <div className="flex justify-end gap-2">
          <button
            onClick={onCancel}
            disabled={canceling}
            className="rounded bg-zinc-800 px-3 py-1.5 text-sm text-zinc-200 hover:bg-zinc-700 disabled:opacity-50"
          >
            {canceling ? t('export.canceling') : t('common.cancel')}
          </button>
          <button
            onClick={() => onConfirm()}
            disabled={busy || !outputRoot.trim()}
            data-testid="confirm-export"
            className="rounded bg-blue-700 px-3 py-1.5 text-sm text-white hover:bg-blue-600 disabled:opacity-50"
          >
            {busy ? t('common.exporting') : t('common.export')}
          </button>
          </div>
        </div>
      </div>
    </div>
  )
}

interface ClipWindowControlProps {
  id: string
  pre: number
  post: number
  onPreChange(value: number): void
  onPostChange(value: number): void
}

function ClipWindowControl({ id, pre, post, onPreChange, onPostChange }: ClipWindowControlProps) {
  const { t } = useI18n()
  const prePct = 50 - (pre / CLIP_MAX_SEC) * 50
  const postPct = 50 + (post / CLIP_MAX_SEC) * 50

  return (
    <div className="grid grid-cols-[42px_1fr_42px] items-center gap-2 text-xs text-zinc-500">
      <span className="text-right tabular-nums">-{pre}s</span>
      <div className="relative h-8">
        <div className="absolute left-0 right-0 top-1/2 h-1.5 -translate-y-1/2 rounded-full bg-zinc-800" />
        <div
          className="absolute top-1/2 h-1.5 -translate-y-1/2 rounded-full bg-blue-600/80"
          style={{ left: `${prePct}%`, width: `${postPct - prePct}%` }}
        />
        <div className="absolute left-1/2 top-1/2 h-5 w-px -translate-y-1/2 bg-zinc-400" title={t('bug.markerTime')} />
        <div
          className="pointer-events-none absolute top-1/2 h-4 w-4 -translate-x-1/2 -translate-y-1/2 rounded-full border border-blue-200 bg-blue-500 shadow"
          style={{ left: `${prePct}%` }}
        />
        <div
          className="pointer-events-none absolute top-1/2 h-4 w-4 -translate-x-1/2 -translate-y-1/2 rounded-full border border-blue-200 bg-blue-500 shadow"
          style={{ left: `${postPct}%` }}
        />
        <input
          dir="rtl"
          type="range"
          min={CLIP_MIN_SEC}
          max={CLIP_MAX_SEC}
          step={0.1}
          value={pre}
          onChange={(e) => onPreChange(Number(e.target.value))}
          data-testid={`pre-${id}`}
          aria-label={t('bug.preAria')}
          className="absolute left-0 top-0 h-8 w-1/2 cursor-ew-resize opacity-0"
        />
        <input
          type="range"
          min={CLIP_MIN_SEC}
          max={CLIP_MAX_SEC}
          step={0.1}
          value={post}
          onChange={(e) => onPostChange(Number(e.target.value))}
          data-testid={`post-${id}`}
          aria-label={t('bug.postAria')}
          className="absolute left-1/2 top-0 h-8 w-1/2 cursor-ew-resize opacity-0"
        />
      </div>
      <span className="tabular-nums">+{post}s</span>
    </div>
  )
}

interface SeveritySelectProps {
  bugId: string
  value: BugSeverity
  severities: SeveritySettings
  visibleSeverities: BugSeverity[]
  onChange(severity: BugSeverity): void
}

function SeveritySelect({ bugId, value, severities, visibleSeverities, onChange }: SeveritySelectProps) {
  const [open, setOpen] = useState(false)
  const rootRef = useRef<HTMLDivElement>(null)
  const color = severityColor(severities, value)
  useEffect(() => {
    if (!open) return
    function onDoc(event: globalThis.MouseEvent) {
      if (!rootRef.current?.contains(event.target as Node)) setOpen(false)
    }
    document.addEventListener('mousedown', onDoc)
    return () => document.removeEventListener('mousedown', onDoc)
  }, [open])
  return (
    <div ref={rootRef} className="relative flex items-center gap-2" data-row-click-ignore="true">
      <select
        value={value}
        onChange={(e) => onChange(e.target.value as BugSeverity)}
        data-testid={`severity-select-${bugId}`}
        aria-hidden="true"
        tabIndex={-1}
        className="sr-only"
      >
        {visibleSeverities.map(severity => (
          <option key={severity} value={severity}>{severityLabel(severities, severity)}</option>
        ))}
      </select>
      <button
        type="button"
        onClick={() => setOpen(v => !v)}
        data-testid={`severity-button-${bugId}`}
        aria-label="Marker severity"
        className="inline-flex max-w-40 items-center gap-2 rounded px-3 py-1.5 text-sm font-semibold text-black outline-none focus:ring-2 focus:ring-blue-600"
        style={{ backgroundColor: color }}
      >
        <span className="truncate">{severityLabel(severities, value)}</span>
        <span className="text-black/70">v</span>
      </button>
      {open && (
        <div className="absolute left-0 top-full z-40 mt-1 min-w-40 overflow-hidden rounded border border-zinc-700 bg-zinc-950 shadow-xl">
          {visibleSeverities.map(severity => (
            <button
              key={severity}
              type="button"
              onClick={() => {
                setOpen(false)
                onChange(severity)
              }}
              className="flex w-full items-center justify-between gap-3 px-3 py-2 text-left text-sm text-black hover:brightness-110"
              style={{ backgroundColor: severityColor(severities, severity) }}
            >
              <span className="truncate">{severityLabel(severities, severity)}</span>
              {severity === value && <span aria-hidden="true">✓</span>}
            </button>
          ))}
        </div>
      )}
    </div>
  )
}

interface MentionOption {
  id: string
  label: string
  detail: string
  hasSlack: boolean
  hasGitLab: boolean
  hasGoogle: boolean
  slackUserId?: string
}

interface MentionPickerProps {
  options: MentionOption[]
  selectedIds: string[]
  aliases: Record<string, string>
  dropdownMode?: 'absolute' | 'fixed'
  onChange(ids: string[]): void
}

interface SlackChannelPickerProps {
  channels: SlackChannel[]
  value: string
  disabled?: boolean
  loading?: boolean
  onOpen?(): void
  onChange(id: string): void
}

interface GitLabProjectPickerProps {
  projects: GitLabProject[]
  value: string
  disabled?: boolean
  loading?: boolean
  onOpen?(): void
  onChange(projectId: string): void
}

function SlackChannelPicker({ channels, value, disabled = false, loading = false, onOpen, onChange }: SlackChannelPickerProps) {
  const [open, setOpen] = useState(false)
  const [query, setQuery] = useState('')
  const rootRef = useRef<HTMLDivElement>(null)
  const selected = channels.find(channel => channel.id === value)
  const normalizedQuery = query.trim().toLowerCase()
  const filteredChannels = normalizedQuery
    ? channels.filter(channel => [
        channel.name,
        channel.id,
        slackChannelLabel(channel),
      ].some(text => text.toLowerCase().includes(normalizedQuery)))
    : channels

  useEffect(() => {
    if (!open) return
    function onDoc(event: globalThis.MouseEvent) {
      if (!rootRef.current?.contains(event.target as Node)) setOpen(false)
    }
    document.addEventListener('mousedown', onDoc)
    return () => document.removeEventListener('mousedown', onDoc)
  }, [open])

  function toggleOpen() {
    if (disabled) return
    setOpen(prev => {
      const next = !prev
      if (next) onOpen?.()
      return next
    })
  }

  return (
    <div ref={rootRef} className="relative mt-1" data-row-click-ignore="true">
      <button
        type="button"
        disabled={disabled}
        onClick={toggleOpen}
        className="flex w-full items-center justify-between gap-2 rounded bg-zinc-900 px-3 py-2 text-left text-sm text-zinc-200 outline-none hover:bg-zinc-800 focus:ring-1 focus:ring-blue-600 disabled:opacity-50"
      >
        <span className="min-w-0 truncate">{selected ? slackChannelLabel(selected) : (loading ? 'Loading channels...' : 'Select Slack channel')}</span>
        <span className="shrink-0 text-zinc-500">v</span>
      </button>
      {open && (
        <div className="absolute z-50 mt-1 w-full rounded border border-zinc-700 bg-zinc-950 shadow-xl">
          <div className="border-b border-zinc-800 p-2">
            <input
              value={query}
              onChange={(event) => setQuery(event.target.value)}
              autoFocus
              placeholder="Search channels"
              className="w-full rounded bg-zinc-900 px-2 py-1.5 text-sm text-zinc-200 outline-none focus:ring-1 focus:ring-blue-600"
            />
          </div>
          <div className="max-h-60 overflow-y-auto py-1">
            {loading && (
              <div className="px-3 py-2 text-sm text-zinc-500">Loading channels...</div>
            )}
            {!loading && filteredChannels.length === 0 && (
              <div className="px-3 py-2 text-sm text-zinc-500">{channels.length === 0 ? 'No channels loaded' : 'No matching channels'}</div>
            )}
            {filteredChannels.map(channel => (
              <button
                key={channel.id}
                type="button"
                onClick={() => {
                  onChange(channel.id)
                  setOpen(false)
                  setQuery('')
                }}
                className={`flex w-full items-center justify-between gap-3 px-3 py-2 text-left text-sm hover:bg-zinc-800 ${channel.id === value ? 'bg-blue-950/60 text-blue-100' : 'text-zinc-200'}`}
              >
                <span className="min-w-0 truncate">{slackChannelLabel(channel)}</span>
                <span className="shrink-0 text-[11px] text-zinc-500">{channel.isMember === false ? 'not joined' : ''}</span>
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

function GitLabProjectPicker({ projects, value, disabled = false, loading = false, onOpen, onChange }: GitLabProjectPickerProps) {
  const [open, setOpen] = useState(false)
  const [query, setQuery] = useState('')
  const rootRef = useRef<HTMLDivElement>(null)
  const selected = projects.find(project => project.pathWithNamespace === value)
  const normalizedQuery = query.trim().toLowerCase()
  const filteredProjects = normalizedQuery
    ? projects.filter(project => [
        project.name,
        project.nameWithNamespace,
        project.pathWithNamespace,
      ].some(text => text.toLowerCase().includes(normalizedQuery)))
    : projects
  const canUseQuery = query.trim() && !projects.some(project => project.pathWithNamespace === query.trim())

  useEffect(() => {
    if (!open) return
    function onDoc(event: globalThis.MouseEvent) {
      if (!rootRef.current?.contains(event.target as Node)) setOpen(false)
    }
    document.addEventListener('mousedown', onDoc)
    return () => document.removeEventListener('mousedown', onDoc)
  }, [open])

  function toggleOpen() {
    if (disabled) return
    setOpen(prev => {
      const next = !prev
      if (next) {
        setQuery(value)
        onOpen?.()
      }
      return next
    })
  }

  function commitProject(projectId: string) {
    onChange(projectId)
    setQuery(projectId)
    setOpen(false)
  }

  return (
    <div ref={rootRef} className="relative mt-1" data-row-click-ignore="true">
      <button
        type="button"
        disabled={disabled}
        onClick={toggleOpen}
        className="flex w-full items-center justify-between gap-2 rounded bg-zinc-950 px-3 py-2 text-left text-sm text-zinc-200 outline-none hover:bg-zinc-900 focus:ring-1 focus:ring-blue-600 disabled:opacity-50"
      >
        <span className="min-w-0 truncate">{selected ? selected.nameWithNamespace : (value || (loading ? 'Loading projects...' : 'Select GitLab project'))}</span>
        <span className="shrink-0 text-zinc-500">v</span>
      </button>
      {open && (
        <div className="absolute z-50 mt-1 w-full rounded border border-zinc-700 bg-zinc-950 shadow-xl">
          <div className="border-b border-zinc-800 p-2">
            <input
              value={query}
              onChange={(event) => setQuery(event.target.value)}
              onKeyDown={(event) => {
                if (event.key === 'Enter' && query.trim()) commitProject(query.trim())
              }}
              autoFocus
              placeholder="Search or enter group/project"
              className="w-full rounded bg-zinc-900 px-2 py-1.5 text-sm text-zinc-200 outline-none focus:ring-1 focus:ring-blue-600"
            />
          </div>
          <div className="max-h-60 overflow-y-auto py-1">
            {loading && (
              <div className="px-3 py-2 text-sm text-zinc-500">Loading projects...</div>
            )}
            {!loading && canUseQuery && (
              <button
                type="button"
                onClick={() => commitProject(query.trim())}
                className="flex w-full items-center justify-between gap-3 px-3 py-2 text-left text-sm text-blue-100 hover:bg-zinc-800"
              >
                <span className="min-w-0 truncate">Use {query.trim()}</span>
                <span className="shrink-0 text-[11px] text-zinc-500">custom</span>
              </button>
            )}
            {!loading && filteredProjects.length === 0 && !canUseQuery && (
              <div className="px-3 py-2 text-sm text-zinc-500">{projects.length === 0 ? 'No projects loaded' : 'No matching projects'}</div>
            )}
            {filteredProjects.map(project => (
              <button
                key={project.id}
                type="button"
                onClick={() => commitProject(project.pathWithNamespace)}
                className={`flex w-full items-center justify-between gap-3 px-3 py-2 text-left text-sm hover:bg-zinc-800 ${project.pathWithNamespace === value ? 'bg-blue-950/60 text-blue-100' : 'text-zinc-200'}`}
              >
                <span className="min-w-0 truncate">{project.nameWithNamespace}</span>
                <span className="max-w-32 shrink-0 truncate text-[11px] text-zinc-500">{project.pathWithNamespace}</span>
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

function MentionPicker({ options, selectedIds, aliases, dropdownMode = 'absolute', onChange }: MentionPickerProps) {
  const [open, setOpen] = useState(false)
  const [query, setQuery] = useState('')
  const [fixedMenuStyle, setFixedMenuStyle] = useState<CSSProperties | undefined>(undefined)
  const rootRef = useRef<HTMLDivElement>(null)
  const selected = new Set(selectedIds)
  const optionMap = new Map(options.map(option => [option.id, option]))
  const slackOptionMap = new Map(options.flatMap(option => option.slackUserId ? [[option.slackUserId, option] as const] : []))
  const labels = selectedIds.map(id => aliases[id] || optionMap.get(id)?.label || slackOptionMap.get(id)?.label || id)
  const normalizedQuery = query.trim().toLowerCase()
  const filteredOptions = normalizedQuery
    ? options.filter(option => [
        option.label,
        option.detail,
        option.id,
        option.hasSlack ? 'slack' : '',
        option.hasGitLab ? 'gitlab' : '',
        option.hasGoogle ? 'google' : '',
      ].some(value => value.toLowerCase().includes(normalizedQuery)))
    : options

  function optionSelected(option: MentionOption): boolean {
    return selected.has(option.id) || Boolean(option.slackUserId && selected.has(option.slackUserId))
  }

  function toggle(option: MentionOption) {
    const next = new Set(selected)
    if (optionSelected(option)) {
      next.delete(option.id)
      if (option.slackUserId) next.delete(option.slackUserId)
    } else {
      next.add(option.id)
    }
    onChange([...next])
  }

  useEffect(() => {
    if (!open) return
    function updateFixedMenuStyle() {
      if (dropdownMode !== 'fixed') return
      const rect = rootRef.current?.getBoundingClientRect()
      if (!rect) return
      const gap = 4
      const margin = 16
      const width = Math.min(320, window.innerWidth - margin * 2)
      const maxHeight = Math.min(256, window.innerHeight - margin * 2)
      const left = Math.max(16, Math.min(rect.left, window.innerWidth - width - 16))
      const opensAbove = rect.bottom + gap + maxHeight > window.innerHeight - margin && rect.top > window.innerHeight - rect.bottom
      const top = opensAbove
        ? Math.max(margin, rect.top - gap - maxHeight)
        : Math.min(rect.bottom + gap, window.innerHeight - margin - maxHeight)
      setFixedMenuStyle({ position: 'fixed', top, left, width, maxHeight })
    }
    updateFixedMenuStyle()
    function onPointerDown(event: PointerEvent) {
      const target = event.target as Node | null
      if (target && rootRef.current?.contains(target)) return
      setOpen(false)
    }
    function onKeyDown(event: KeyboardEvent) {
      if (event.key === 'Escape') setOpen(false)
    }
    document.addEventListener('pointerdown', onPointerDown)
    document.addEventListener('keydown', onKeyDown)
    window.addEventListener('resize', updateFixedMenuStyle)
    window.addEventListener('scroll', updateFixedMenuStyle, true)
    return () => {
      document.removeEventListener('pointerdown', onPointerDown)
      document.removeEventListener('keydown', onKeyDown)
      window.removeEventListener('resize', updateFixedMenuStyle)
      window.removeEventListener('scroll', updateFixedMenuStyle, true)
    }
  }, [dropdownMode, open])

  return (
    <div ref={rootRef} className="relative" data-row-click-ignore="true">
      <button
        type="button"
        onClick={() => setOpen(value => !value)}
        className="max-w-full rounded bg-zinc-800 px-2 py-1 text-left text-[11px] text-zinc-300 hover:bg-zinc-700"
      >
        {labels.length > 0 ? `Mention: ${labels.join(', ')}` : 'Mention people'}
      </button>
      {open && (
        <div
          style={dropdownMode === 'fixed' ? fixedMenuStyle : undefined}
          className={`${dropdownMode === 'fixed' ? 'fixed z-[70]' : 'absolute z-20 mt-1 w-80'} max-h-64 max-w-[calc(100vw-2rem)] overflow-auto rounded border border-zinc-700 bg-zinc-950 p-1 shadow-xl`}
        >
          {options.length > 0 && (
            <input
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Search people"
              className="mb-1 w-full rounded bg-zinc-900 px-2 py-1.5 text-xs text-zinc-200 outline-none focus:ring-1 focus:ring-blue-600"
              autoFocus
            />
          )}
          {options.length === 0 ? (
            <div className="px-2 py-2 text-xs text-zinc-500">Refresh Slack or GitLab users in Publish settings.</div>
          ) : filteredOptions.length === 0 ? (
            <div className="px-2 py-2 text-xs text-zinc-500">No matching people.</div>
          ) : filteredOptions.map(option => (
            <label key={option.id} className="flex cursor-pointer items-start gap-2 rounded px-2 py-1.5 text-xs text-zinc-300 hover:bg-zinc-900">
              <input
                type="checkbox"
                checked={optionSelected(option)}
                onChange={() => toggle(option)}
                className="mt-0.5 h-4 w-4 accent-blue-600"
              />
              <span className="min-w-0 flex-1">
                <span className="block truncate">{option.label}</span>
                <span className="mt-1 flex flex-wrap gap-1">
                  <MentionProviderBadges hasSlack={option.hasSlack} hasGitLab={option.hasGitLab} hasGoogle={option.hasGoogle} />
                </span>
              </span>
              <span className="max-w-24 shrink-0 truncate text-[10px] text-zinc-600">{option.detail || option.id}</span>
            </label>
          ))}
        </div>
      )}
    </div>
  )
}

interface OriginalFilesWarningDialogProps {
  remember: boolean
  onRememberChange(value: boolean): void
  onCancel(): void
  onConfirm(): void
}

function OriginalFilesWarningDialog({ remember, onRememberChange, onCancel, onConfirm }: OriginalFilesWarningDialogProps) {
  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/70 p-4" data-testid="original-files-warning">
      <div className="w-full max-w-md rounded-lg border border-amber-700 bg-zinc-900 p-4 shadow-2xl">
        <div className="text-sm font-semibold text-amber-200">輸出全時長錄影可能會很大</div>
        <div className="mt-2 text-xs leading-5 text-zinc-400">
          Loupe 會把全時長錄影輸出到本機輸出資料夾。這個檔案只會本地輸出，不會上傳到 Slack 或 GitLab；檔案可能很大，輸出時間和磁碟空間用量都會增加。
        </div>
        <label className="mt-4 flex items-center gap-2 text-xs text-zinc-300">
          <input
            type="checkbox"
            checked={remember}
            onChange={(e) => onRememberChange(e.target.checked)}
            className="h-4 w-4 accent-blue-600"
          />
          以後不再詢問
        </label>
        <div className="mt-4 flex justify-end gap-2">
          <button
            type="button"
            onClick={onCancel}
            className="rounded bg-zinc-800 px-3 py-1.5 text-sm text-zinc-200 hover:bg-zinc-700"
          >
            取消
          </button>
          <button
            type="button"
            onClick={onConfirm}
            className="rounded bg-amber-600 px-3 py-1.5 text-sm text-white hover:bg-amber-500"
          >
            繼續輸出
          </button>
        </div>
      </div>
    </div>
  )
}

export const BugList = forwardRef<BugListHandle, Props>(function BugList({ api, sessionId, bugs, selectedBugId, onSelect, onMutated, allowExport = true, autoFocusLatest = false, buildVersion = '', tester = '', testNote = '', hasSessionMicTrack = false, markerToolbar }: Props, ref) {
  const { t } = useI18n()
  const [thumbs, setThumbs] = useState<Record<string, string>>({})
  const [nowMs, setNowMs] = useState(Date.now())
  const [logcatPreview, setLogcatPreview] = useState<Record<string, string>>({})
  const [expandedLogcatIds, setExpandedLogcatIds] = useState<Set<string>>(new Set())
  const [exporting, setExporting] = useState(false)
  const [cancelingExport, setCancelingExport] = useState(false)
  const [exportRequest, setExportRequest] = useState<ExportRequest | null>(null)
  const [exportRoot, setExportRoot] = useState('')
  const [exportReportTitle, setExportReportTitle] = useState('Loupe QA Report')
  const [exportBuildVersion, setExportBuildVersion] = useState(buildVersion)
  const [exportTester, setExportTester] = useState(tester)
  const [exportTestNote, setExportTestNote] = useState(testNote)
  const [exportIncludeLogcat, setExportIncludeLogcat] = useState(false)
  const [exportIncludeMicTrack, setExportIncludeMicTrack] = useState(false)
  const [exportIncludeOriginalFiles, setExportIncludeOriginalFiles] = useState(false)
  const [exportMergeOriginalAudio, setExportMergeOriginalAudio] = useState(false)
  const [showOriginalFilesWarning, setShowOriginalFilesWarning] = useState(false)
  const [rememberOriginalFilesWarning, setRememberOriginalFilesWarning] = useState(false)
  const [publishSlack, setPublishSlack] = useState(false)
  const [publishGitLab, setPublishGitLab] = useState(false)
  const [publishGoogleDrive, setPublishGoogleDrive] = useState(false)
  const [slackSettings, setSlackSettings] = useState<SlackPublishSettings | null>(null)
  const [slackConnecting, setSlackConnecting] = useState(false)
  const [slackThreadMode, setSlackThreadMode] = useState<SlackThreadMode>('per-marker-thread')
  const [slackChannelId, setSlackChannelId] = useState('')
  const [slackChannels, setSlackChannels] = useState<SlackChannel[]>([])
  const [slackMentionIds, setSlackMentionIds] = useState<string[]>([])
  const [slackManualMentionInput, setSlackManualMentionInput] = useState('')
  const [slackDirectoryRefreshing, setSlackDirectoryRefreshing] = useState(false)
  const [slackDirectoryError, setSlackDirectoryError] = useState('')
  const slackDirectoryRefreshPromiseRef = useRef<Promise<Awaited<ReturnType<DesktopApi['settings']['get']> | null>> | null>(null)
  const [gitlabSettings, setGitLabSettings] = useState<GitLabPublishSettings | null>(null)
  const [gitlabMode, setGitLabMode] = useState<GitLabPublishMode>('single-issue')
  const [gitlabProjectId, setGitLabProjectId] = useState('')
  const [gitlabProjects, setGitLabProjects] = useState<GitLabProject[]>([])
  const [gitlabProjectsRefreshing, setGitLabProjectsRefreshing] = useState(false)
  const [gitlabProjectsError, setGitLabProjectsError] = useState('')
  const [googleSettings, setGoogleSettings] = useState<GooglePublishSettings | null>(null)
  const [exportError, setExportError] = useState('')
  const [exportId, setExportId] = useState<string | null>(null)
  const [exportProgress, setExportProgress] = useState<ExportProgress | null>(null)
  const [severities, setSeverities] = useState<SeveritySettings>(DEFAULT_SEVERITIES)
  const [slackUsers, setSlackUsers] = useState<SlackMentionUser[]>([])
  const [slackAliases, setSlackAliases] = useState<Record<string, string>>({})
  const [mentionIdentities, setMentionIdentities] = useState<MentionIdentity[]>([])
  const visibleSeverityList = useMemo(() => visibleSeverities(severities), [severities])
  const mentionOptions = useMemo<MentionOption[]>(() => {
    const options = mentionIdentities.map(identity => {
      const details = [
        identity.email || identity.googleEmail || '',
        identity.gitlabUsername ? `@${identity.gitlabUsername}` : '',
        identity.slackUserId || '',
      ].filter(Boolean)
      return {
        id: identity.id,
        label: mentionIdentityLabel(identity),
        detail: details.join(' / '),
        hasSlack: Boolean(identity.slackUserId),
        hasGitLab: Boolean(identity.gitlabUsername),
        hasGoogle: Boolean(identity.googleEmail),
        slackUserId: identity.slackUserId,
      }
    })
    const identityIds = new Set(options.map(option => option.id))
    const identitySlackIds = new Set(options.map(option => option.slackUserId).filter(Boolean))
    for (const user of slackUsers) {
      if (identityIds.has(user.id) || identitySlackIds.has(user.id)) continue
      options.push({
        id: user.id,
        label: slackUserLabel(user),
        detail: user.id,
        hasSlack: true,
        hasGitLab: false,
        hasGoogle: false,
        slackUserId: user.id,
      })
    }
    return options.sort((a, b) => a.label.localeCompare(b.label))
  }, [mentionIdentities, slackUsers])
  const knownBugIdsRef = useRef<Set<string>>(new Set())

  useEffect(() => {
    api.settings.get().then(settings => {
      setSeverities(settings.severities)
      setSlackSettings(settings.slack)
      const fetchedUsers = (settings.slack.mentionUsers ?? []).filter(user => !user.deleted && !user.isBot)
      const fetchedIds = new Set(fetchedUsers.map(user => user.id))
      const fallbackUsers = (settings.slack.mentionUserIds ?? [])
        .filter(id => !fetchedIds.has(id))
        .map(id => ({ id, name: '', displayName: settings.slack.mentionAliases?.[id] ?? id, realName: '' }))
      setSlackUsers([...fetchedUsers, ...fallbackUsers])
      setSlackAliases(settings.slack.mentionAliases ?? {})
      setSlackChannels((settings.slack.channels ?? []).filter(channel => !channel.isArchived))
      setGitLabSettings(settings.gitlab)
      setGitLabProjectId(settings.gitlab.projectId)
      setGitLabMode(settings.gitlab.mode)
      setGoogleSettings(settings.google)
      setMentionIdentities(settings.mentionIdentities ?? [])
    }).catch(() => {})
  }, [api])

  useEffect(() => api.onSlackOAuthCompleted((result) => {
    setSlackConnecting(false)
    if (result.ok && result.settings) {
      setSlackSettings(result.settings.slack)
      applySlackDirectory(result.settings)
      setSlackChannelId(channelIdFromSettings(result.settings.slack))
      setSlackMentionIds(result.settings.slack.mentionUserIds ?? [])
      setSlackManualMentionInput(formatManualSlackMentions(result.settings.slack.mentionUserIds ?? []))
      setPublishSlack(isSlackConnected(result.settings.slack))
      setSlackDirectoryError('')
    } else {
      setSlackDirectoryError(result.error || 'Slack connection failed.')
    }
  }), [api])

  useEffect(() => {
    const hasPendingThumbnail = bugs.some(b => !b.screenshotRel && nowMs - b.createdAt < THUMB_PENDING_MS)
    if (!hasPendingThumbnail) return
    const timer = window.setTimeout(() => setNowMs(Date.now()), 1000)
    return () => window.clearTimeout(timer)
  }, [bugs, nowMs])

  useEffect(() => api.onBugExportProgress((progress) => {
    setExportProgress(prev => {
      if (progress.exportId !== exportId) return prev
      return progress
    })
  }), [api, exportId])

  useEffect(() => {
    let cancelled = false
    Promise.all(
      bugs
        .filter(b => b.screenshotRel)
        .map(async b => {
          const abs = await api._resolveAssetPath(b.sessionId, b.screenshotRel!)
          return [b.id, localFileUrl(abs)] as const
        })
    ).then(entries => {
      if (cancelled) return
      const next: Record<string, string> = {}
      for (const [id, url] of entries) next[id] = url
      setThumbs(next)
    })
    return () => { cancelled = true }
  }, [bugs, api])

  useEffect(() => {
    let cancelled = false
    Promise.all(
      bugs
        .filter(b => b.logcatRel)
        .map(async b => {
          const preview = await api.bug.getLogcatPreview({ sessionId: b.sessionId, relPath: b.logcatRel! })
          return [b.id, preview ?? ''] as const
        })
    ).then(entries => {
      if (cancelled) return
      const next: Record<string, string> = {}
      for (const [id, preview] of entries) {
        if (preview) next[id] = preview
      }
      setLogcatPreview(next)
    })
    return () => { cancelled = true }
  }, [bugs, api])

  useEffect(() => {
    const bugIds = new Set(bugs.map(b => b.id))
    setExpandedLogcatIds(prev => new Set([...prev].filter(id => bugIds.has(id))))
  }, [bugs])

  function applySlackDirectory(settings: Awaited<ReturnType<DesktopApi['settings']['get']>>): void {
    const fetchedUsers = (settings.slack.mentionUsers ?? []).filter(user => !user.deleted && !user.isBot)
    const fetchedIds = new Set(fetchedUsers.map(user => user.id))
    const fallbackUsers = (settings.slack.mentionUserIds ?? [])
      .filter(id => !fetchedIds.has(id) && !id.startsWith('!'))
      .map(id => ({ id, name: '', displayName: settings.slack.mentionAliases?.[id] ?? id, realName: '' }))
    setSlackUsers([...fetchedUsers, ...fallbackUsers])
    setSlackAliases(settings.slack.mentionAliases ?? {})
    setSlackChannels((settings.slack.channels ?? []).filter(channel => !channel.isArchived))
    setMentionIdentities(settings.mentionIdentities ?? [])
  }

  async function refreshSlackDirectoryForExport(): Promise<Awaited<ReturnType<DesktopApi['settings']['get']>> | null> {
    if (slackDirectoryRefreshPromiseRef.current) return slackDirectoryRefreshPromiseRef.current
    setSlackDirectoryRefreshing(true)
    setSlackDirectoryError('')
    const refreshPromise = (async () => {
      const settings = await withTimeout(
        api.settings.refreshSlackChannels(),
        15000,
        'Slack channel loading timed out. Try Refresh again in a minute.',
      )
      setSlackSettings(settings.slack)
      applySlackDirectory(settings)
      setSlackChannelId(channelIdFromSettings(settings.slack))
      if ((settings.slack.channels ?? []).length === 0) {
        setSlackDirectoryError('Slack connected, but no channels were returned.')
      }
      return settings
    })()
    slackDirectoryRefreshPromiseRef.current = refreshPromise
    try {
      return await refreshPromise
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      setSlackDirectoryError(/ratelimited|rate.?limited/i.test(message)
        ? 'Slack rate limit reached. Keep the selected channel ID or try Refresh again in a minute.'
        : message)
      return null
    } finally {
      slackDirectoryRefreshPromiseRef.current = null
      setSlackDirectoryRefreshing(false)
    }
  }

  async function beginExport(request: ExportRequest) {
    let settings: Awaited<ReturnType<DesktopApi['settings']['get']>>
    try {
      settings = await api.settings.get()
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      setExportError(message || 'Could not open export dialog')
      if (typeof window.alert === 'function') window.alert(message)
      return
    }
    setSlackDirectoryError('')
    setGitLabProjectsError('')
    setExportRoot(settings.exportRoot)
    setExportReportTitle('Loupe QA Report')
    setExportBuildVersion(buildVersion)
    setExportTester(tester)
    setExportTestNote(testNote)
    setExportIncludeLogcat(request.bugs.some(b => Boolean(b.logcatRel)))
    setExportIncludeMicTrack(false)
    setExportIncludeOriginalFiles(false)
    setExportMergeOriginalAudio(false)
    setShowOriginalFilesWarning(false)
    setRememberOriginalFilesWarning(false)
    setPublishSlack(false)
    setPublishGitLab(false)
    setPublishGoogleDrive(false)
    setSlackThreadMode('per-marker-thread')
    setSlackSettings(settings.slack)
    setSlackChannelId(channelIdFromSettings(settings.slack))
    setSlackMentionIds(settings.slack.mentionUserIds ?? [])
    setSlackManualMentionInput(formatManualSlackMentions(settings.slack.mentionUserIds ?? []))
    applySlackDirectory(settings)
    setGitLabSettings(settings.gitlab)
    setGitLabProjectId(settings.gitlab.projectId)
    setGitLabMode(settings.gitlab.mode)
    setGoogleSettings(settings.google)
    setExportError('')
    setExportProgress(null)
    setExportId(null)
    setCancelingExport(false)
    setExportRequest(request)
  }

  async function connectSlackForExport() {
    setSlackConnecting(true)
    setSlackDirectoryError('')
    setExportError('')
    try {
      const settings = await api.settings.get()
      setSlackSettings(settings.slack)
      const nextSettings = await api.settings.startSlackUserOAuth(settings.slack)
      setSlackSettings(nextSettings.slack)
      applySlackDirectory(nextSettings)
      setSlackChannelId(channelIdFromSettings(nextSettings.slack))
      setSlackMentionIds(nextSettings.slack.mentionUserIds ?? [])
      setSlackManualMentionInput(formatManualSlackMentions(nextSettings.slack.mentionUserIds ?? []))
      if (isSlackConnected(nextSettings.slack)) {
        setPublishSlack(true)
        setSlackConnecting(false)
      }
    } catch (err) {
      setSlackConnecting(false)
      setSlackDirectoryError(err instanceof Error ? err.message : String(err))
    }
  }

  async function exportAll() {
    const bugIds = bugs.map(b => b.id)
    await beginExport({ bugs, bugIds })
  }

  async function refreshGitLabProjectsForExport() {
    const sourceSettings = gitlabSettings ?? (await api.settings.get()).gitlab
    const nextGitLab = {
      ...sourceSettings,
      projectId: gitlabProjectId.trim() || sourceSettings.projectId,
      mode: gitlabMode,
    }
    setGitLabProjectsRefreshing(true)
    setGitLabProjectsError('')
    try {
      const projects = await withTimeout(
        api.settings.listGitLabProjects(nextGitLab),
        15000,
        'GitLab project loading timed out. Try Refresh again in a minute.',
      )
      setGitLabSettings(nextGitLab)
      setGitLabProjects([...projects].sort((a, b) => a.nameWithNamespace.localeCompare(b.nameWithNamespace)))
      if (projects.length === 0) setGitLabProjectsError('GitLab connected, but no projects were returned.')
    } catch (err) {
      setGitLabProjectsError(err instanceof Error ? err.message : String(err))
    } finally {
      setGitLabProjectsRefreshing(false)
    }
  }

  useImperativeHandle(ref, () => ({
    exportAll: () => { void exportAll() },
    exporting,
  }))

  async function confirmExport(skipOriginalFilesWarning = false) {
    if (!exportRequest) return
    const trimmedRoot = exportRoot.trim()
    if (!trimmedRoot) return
    if (publishSlack && !isSlackConnected(slackSettings)) {
      setExportError('Connect Slack before exporting to Slack.')
      return
    }
    if (publishSlack && !slackChannelId.trim()) {
      setExportError('Select a Slack channel before exporting.')
      return
    }
    if (publishGitLab && !isGitLabConnected(gitlabSettings)) {
      setExportError('Connect GitLab before exporting to GitLab.')
      return
    }
    if (publishGitLab && !gitlabProjectId.trim()) {
      setExportError('Select a GitLab project before exporting.')
      return
    }
    if (publishGoogleDrive && !isGoogleDriveConnected(googleSettings)) {
      setExportError('Connect Google Drive and choose a Drive folder before exporting to Google Drive.')
      return
    }
    if (exportIncludeOriginalFiles && !skipOriginalFilesWarning && localStorage.getItem(ORIGINAL_FILES_WARNING_KEY) !== '1') {
      setRememberOriginalFilesWarning(false)
      setShowOriginalFilesWarning(true)
      return
    }
    const nextExportId = `${Date.now()}-${Math.random().toString(16).slice(2)}`
    setExportId(nextExportId)
    setExportProgress({
      exportId: nextExportId,
      phase: 'prepare',
      message: t('export.progressStarting'),
      detail: t('export.progressUpdatingMetadata'),
      current: 0,
      total: Math.max(1, 1 + exportRequest.bugIds.length * 3),
      clipIndex: 0,
      clipCount: exportRequest.bugIds.length,
      remaining: exportRequest.bugIds.length,
    })
    setExporting(true)
    setExportError('')
    setCancelingExport(false)
    try {
      await api.settings.setExportRoot(trimmedRoot)
      await api.session.updateMetadata(sessionId, {
        buildVersion: exportBuildVersion.trim(),
        tester: exportTester.trim(),
        testNote: exportTestNote.trim(),
      })
      let currentSettings = await api.settings.get()
      if (publishSlack && slackChannelId.trim()) {
        const manualMentions = normalizeManualSlackMentions(slackManualMentionInput)
        const nextMentionIds = Array.from(new Set([
          ...slackMentionIds.filter(id => !id.startsWith('!')),
          ...manualMentions,
        ]))
        const nextSlack: SlackPublishSettings = {
          ...currentSettings.slack,
          channelId: slackChannelId.trim(),
          mentionUserIds: nextMentionIds,
          mentionAliases: slackAliases,
        }
        currentSettings = await api.settings.setSlack(nextSlack)
        setSlackMentionIds(currentSettings.slack.mentionUserIds ?? [])
        setSlackManualMentionInput(formatManualSlackMentions(currentSettings.slack.mentionUserIds ?? []))
      }
      if (publishGitLab && gitlabProjectId.trim()) {
        const nextGitLab: GitLabPublishSettings = {
          ...currentSettings.gitlab,
          projectId: gitlabProjectId.trim(),
          mode: gitlabMode,
        }
        currentSettings = await api.settings.setGitLab(nextGitLab)
        setGitLabSettings(currentSettings.gitlab)
        setGitLabProjectId(currentSettings.gitlab.projectId)
        setGitLabMode(currentSettings.gitlab.mode)
      }
      onMutated()
      const targets: PublishTarget[] = [
        ...(publishSlack ? ['slack' as const] : []),
        ...(publishGitLab ? ['gitlab' as const] : []),
        ...(publishGoogleDrive ? ['google-drive' as const] : []),
      ]
      const publish = {
        target: targets[0] ?? 'local',
        targets: targets.length > 0 ? targets : ['local' as const],
        slackThreadMode,
        gitlabMode,
      }
      const paths = exportRequest.bugIds.length === 1
        ? ([await api.bug.exportClip({ sessionId, bugId: exportRequest.bugIds[0], exportId: nextExportId, reportTitle: exportReportTitle.trim() || 'Loupe QA Report', includeLogcat: exportIncludeLogcat, includeMicTrack: exportIncludeMicTrack, includeOriginalFiles: exportIncludeOriginalFiles, mergeOriginalAudio: exportIncludeOriginalFiles && exportMergeOriginalAudio, publish })].filter(Boolean) as string[])
        : await api.bug.exportClips({ sessionId, bugIds: exportRequest.bugIds, exportId: nextExportId, reportTitle: exportReportTitle.trim() || 'Loupe QA Report', includeLogcat: exportIncludeLogcat, includeMicTrack: exportIncludeMicTrack, includeOriginalFiles: exportIncludeOriginalFiles, mergeOriginalAudio: exportIncludeOriginalFiles && exportMergeOriginalAudio, publish })
      if (paths && paths.length > 0) {
        if (exportRequest.bugIds.length === 0) notifyFullRecordingExported(api, paths[0], t)
        else notifyExported(api, paths[0], paths.length, t)
      }
      setExportRequest(null)
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      if (/cancel/i.test(message)) {
        setExportRequest(null)
        return
      }
      setExportError(message || 'Export failed')
      setExportProgress(prev => prev
        ? { ...prev, phase: 'error', message: t('export.progressFailed'), detail: message }
        : null)
      if (typeof window.alert === 'function') window.alert(message)
    } finally {
      setExporting(false)
      setCancelingExport(false)
    }
  }

  function confirmOriginalFilesWarning() {
    if (rememberOriginalFilesWarning) localStorage.setItem(ORIGINAL_FILES_WARNING_KEY, '1')
    setShowOriginalFilesWarning(false)
    void confirmExport(true)
  }

  async function cancelExport() {
    if (!exporting || !exportId) {
      setExportRequest(null)
      return
    }
    setCancelingExport(true)
    setExportProgress(prev => prev
      ? { ...prev, message: t('export.canceling'), detail: t('export.cancelingDetail') }
      : prev)
    await api.bug.cancelExport(exportId)
  }

  async function browseExportRoot() {
    const settings = await api.settings.chooseExportRoot()
    if (settings) setExportRoot(settings.exportRoot)
  }

  return (
    <div className="min-h-full">
      {markerToolbar && (
        <div className="sticky top-0 z-10 border-b border-zinc-800 bg-zinc-950/95 px-3 py-2 backdrop-blur">
          {markerToolbar}
        </div>
      )}
      <ul className="space-y-1.5 p-2" data-testid="bug-list">
        {bugs.length === 0 && <li className="p-4 text-sm text-zinc-500">{t('bug.noMarkers')}</li>}
        {bugs.map(b => (
          <BugRow
            key={b.id}
            bug={b}
            api={api}
            sessionId={sessionId}
            isSelected={b.id === selectedBugId}
            thumbnailUrl={thumbs[b.id]}
            logcatPreview={logcatPreview[b.id]}
            logcatExpanded={expandedLogcatIds.has(b.id)}
            nowMs={nowMs}
            onSelect={onSelect}
            onMutated={onMutated}
            allowExport={allowExport}
            shouldScrollIntoView={b.id === selectedBugId}
            tester={tester}
            severities={severities}
            visibleSeverities={visibleSeverityList}
            mentionOptions={mentionOptions}
            slackAliases={slackAliases}
            onToggleLogcat={() => setExpandedLogcatIds(prev => {
              const next = new Set(prev)
              if (next.has(b.id)) next.delete(b.id)
              else next.add(b.id)
              return next
            })}
            onExportRequest={(bug) => beginExport({ bugs: [bug], bugIds: [bug.id] })}
          />
        ))}
      </ul>
      {exportRequest && (
        <ExportConfirmDialog
          count={exportRequest.bugIds.length}
          outputRoot={exportRoot}
          reportTitle={exportReportTitle}
          buildVersion={exportBuildVersion}
          tester={exportTester}
          testNote={exportTestNote}
          includeLogcat={exportIncludeLogcat}
          includeMicTrack={exportIncludeMicTrack}
          includeOriginalFiles={exportIncludeOriginalFiles}
          mergeOriginalAudio={exportMergeOriginalAudio}
          hasSessionMicTrack={hasSessionMicTrack}
          hasMarkerAudioNotes={exportRequest.bugs.some(b => Boolean(b.audioRel))}
          slackConnected={isSlackConnected(slackSettings)}
          gitlabConnected={isGitLabConnected(gitlabSettings)}
          googleDriveConnected={isGoogleDriveConnected(googleSettings)}
          slackConnecting={slackConnecting}
          publishSlack={publishSlack}
          publishGitLab={publishGitLab}
          publishGoogleDrive={publishGoogleDrive}
          slackThreadMode={slackThreadMode}
          slackChannels={slackChannels}
          slackChannelId={slackChannelId}
          mentionOptions={mentionOptions}
          slackMentionIds={slackMentionIds}
          slackMentionAliases={slackAliases}
          slackManualMentionInput={slackManualMentionInput}
          slackDirectoryRefreshing={slackDirectoryRefreshing}
          slackDirectoryError={slackDirectoryError}
          gitlabMode={gitlabMode}
          gitlabProjectId={gitlabProjectId}
          gitlabProjects={gitlabProjects}
          gitlabProjectsRefreshing={gitlabProjectsRefreshing}
          gitlabProjectsError={gitlabProjectsError}
          busy={exporting}
          error={exportError}
          canceling={cancelingExport}
          progress={exportProgress}
          hasMissingNotes={exportRequest.bugs.some(b => !b.note.trim())}
          onOutputRootChange={setExportRoot}
          onReportTitleChange={setExportReportTitle}
          onBuildVersionChange={setExportBuildVersion}
          onTesterChange={setExportTester}
          onTestNoteChange={setExportTestNote}
          onIncludeLogcatChange={setExportIncludeLogcat}
          onIncludeMicTrackChange={setExportIncludeMicTrack}
          onIncludeOriginalFilesChange={setExportIncludeOriginalFiles}
          onMergeOriginalAudioChange={setExportMergeOriginalAudio}
          onConnectSlack={() => { void connectSlackForExport() }}
          onPublishSlackChange={setPublishSlack}
          onPublishGitLabChange={(value) => {
            if (value && !isGitLabConnected(gitlabSettings)) return
            setPublishGitLab(value)
            if (value && gitlabProjects.length === 0 && !gitlabProjectsRefreshing) void refreshGitLabProjectsForExport()
          }}
          onPublishGoogleDriveChange={(value) => {
            if (value && !isGoogleDriveConnected(googleSettings)) return
            setPublishGoogleDrive(value)
          }}
          onSlackThreadModeChange={setSlackThreadMode}
          onSlackChannelIdChange={setSlackChannelId}
          onSlackMentionIdsChange={setSlackMentionIds}
          onSlackManualMentionInputChange={setSlackManualMentionInput}
          onRefreshSlackDirectory={() => { void refreshSlackDirectoryForExport() }}
          onGitLabModeChange={setGitLabMode}
          onGitLabProjectIdChange={setGitLabProjectId}
          onRefreshGitLabProjects={() => { void refreshGitLabProjectsForExport() }}
          onBrowseOutputRoot={browseExportRoot}
          onCancel={cancelExport}
          onConfirm={confirmExport}
        />
      )}
      {showOriginalFilesWarning && (
        <OriginalFilesWarningDialog
          remember={rememberOriginalFilesWarning}
          onRememberChange={setRememberOriginalFilesWarning}
          onCancel={() => setShowOriginalFilesWarning(false)}
          onConfirm={confirmOriginalFilesWarning}
        />
      )}
    </div>
  )
})

interface RowProps {
  bug: Bug
  api: DesktopApi
  sessionId: string
  isSelected: boolean
  thumbnailUrl?: string
  logcatPreview?: string
  logcatExpanded: boolean
  nowMs: number
  onSelect(bug: Bug): void
  onMutated(): void
  allowExport: boolean
  shouldScrollIntoView: boolean
  tester: string
  severities: SeveritySettings
  visibleSeverities: BugSeverity[]
  mentionOptions: MentionOption[]
  slackAliases: Record<string, string>
  onToggleLogcat(): void
  onExportRequest(bug: Bug): void
}

function BugRow({ bug, api, sessionId, isSelected, thumbnailUrl, logcatPreview, logcatExpanded, nowMs, onSelect, onMutated, allowExport, shouldScrollIntoView, severities, visibleSeverities, mentionOptions, slackAliases, onToggleLogcat, onExportRequest }: RowProps) {
  const { t } = useI18n()
  const [note, setNote] = useState(bug.note)
  const [pre, setPre] = useState(bug.preSec)
  const [post, setPost] = useState(bug.postSec)
  const [mentionUserIds, setMentionUserIds] = useState(bug.mentionUserIds ?? [])
  const [editingNote, setEditingNote] = useState(false)
  const rowRef = useRef<HTMLLIElement>(null)
  const noteRef = useRef<HTMLTextAreaElement>(null)
  const recorderRef = useRef<MediaRecorder | null>(null)
  const chunksRef = useRef<Blob[]>([])
  const recordStartedAtRef = useRef(0)
  const [recording, setRecording] = useState(false)
  const [transcribing, setTranscribing] = useState(false)

  useEffect(() => { setNote(bug.note) }, [bug.note])
  useEffect(() => { setPre(bug.preSec) }, [bug.preSec])
  useEffect(() => { setPost(bug.postSec) }, [bug.postSec])
  useEffect(() => { setMentionUserIds(bug.mentionUserIds ?? []) }, [bug.mentionUserIds])
  useEffect(() => {
    if (!shouldScrollIntoView) return
    rowRef.current?.scrollIntoView({ block: 'center', behavior: 'smooth' })
  }, [shouldScrollIntoView, bug.id])
  useEffect(() => {
    const el = noteRef.current
    if (!el) return
    el.style.height = 'auto'
    el.style.height = `${el.scrollHeight}px`
  }, [note])

  async function save(patch: Partial<Pick<Bug, 'note' | 'severity' | 'preSec' | 'postSec' | 'mentionUserIds'>>) {
    await api.bug.update(bug.id, {
      note: bug.note,
      severity: bug.severity,
      preSec: bug.preSec,
      postSec: bug.postSec,
      mentionUserIds: bug.mentionUserIds ?? [],
      ...patch,
    })
    onMutated()
  }

  async function commitNote() {
    if (note === bug.note) return
    await save({ note: note.trim() })
  }

  async function changePre(n: number) {
    const v = Math.max(CLIP_MIN_SEC, Math.min(CLIP_MAX_SEC, n))
    setPre(v)
    await save({ preSec: v })
  }

  async function changePost(n: number) {
    const v = Math.max(CLIP_MIN_SEC, Math.min(CLIP_MAX_SEC, n))
    setPost(v)
    await save({ postSec: v })
  }

  async function changeMentions(ids: string[]) {
    setMentionUserIds(ids)
    await save({ mentionUserIds: ids })
  }

  async function del() {
    if (!confirm(t('bug.deleteConfirm'))) return
    await api.bug.delete(bug.id)
    onMutated()
  }

  async function exportClip() {
    onExportRequest(bug)
  }

  async function toggleRecording() {
    if (recording) {
      recorderRef.current?.stop()
      return
    }
    const stream = await navigator.mediaDevices.getUserMedia({ audio: true })
    const recorder = new MediaRecorder(stream)
    chunksRef.current = []
    recordStartedAtRef.current = Date.now()
    recorder.ondataavailable = (event) => {
      if (event.data.size > 0) chunksRef.current.push(event.data)
    }
    recorder.onstop = async () => {
      stream.getTracks().forEach(track => track.stop())
      setRecording(false)
      const blob = new Blob(chunksRef.current, { type: recorder.mimeType || 'audio/webm' })
      if (blob.size === 0) return
      const durationMs = Date.now() - recordStartedAtRef.current
      const base64 = await blobToBase64(blob)
      setTranscribing(true)
      try {
        const result = await api.bug.transcribeAudio({ sessionId, bugId: bug.id, base64, durationMs, mimeType: blob.type })
        const text = result.text.trim()
        if (text) {
          const nextNote = [note.trim(), text].filter(Boolean).join('\n')
          setNote(nextNote)
          await save({ note: nextNote })
        }
      } finally {
        setTranscribing(false)
      }
    }
    recorderRef.current = recorder
    setRecording(true)
    recorder.start()
  }

  function shouldIgnoreRowClick(event: MouseEvent<HTMLElement>): boolean {
    const target = event.target as HTMLElement | null
    return Boolean(target?.closest('button,input,textarea,select,a,[data-row-click-ignore="true"]'))
  }

  return (
    <li
      ref={rowRef}
      data-testid={`bug-row-${bug.id}`}
      onClick={(event) => {
        if (shouldIgnoreRowClick(event)) return
        onSelect(bug)
      }}
      className={`scroll-my-24 cursor-pointer rounded border p-2 transition-colors ${
        isSelected
          ? 'border-blue-700 bg-zinc-900'
          : 'border-zinc-800 bg-zinc-900/50 hover:border-zinc-700 hover:bg-zinc-900'
      }`}
    >
      <div className="flex gap-2">
        <div className="flex shrink-0 flex-col gap-2">
          <SeveritySelect
            bugId={bug.id}
            value={bug.severity}
            severities={severities}
            visibleSeverities={visibleSeverities}
            onChange={(severity) => { if (severity !== bug.severity) save({ severity }) }}
          />
          <button onClick={() => onSelect(bug)} className="shrink-0" title={t('bug.screenshotTitle')}>
            {thumbnailUrl
              ? (
                <img
                  src={thumbnailUrl}
                  alt=""
                  data-testid={`thumb-${bug.id}`}
                  className="h-24 w-28 rounded border border-zinc-800 bg-black object-contain"
                />
              )
              : nowMs - bug.createdAt < THUMB_PENDING_MS
                ? <ThumbnailWaiting label={t('bug.waitingScreenshot')} />
                : <div className="h-24 w-28 rounded border border-zinc-800 bg-zinc-950" />
            }
          </button>
        </div>

        <div className="min-w-0 flex-1 space-y-1">
          <div className="flex min-w-0 items-start gap-2">
            <button onClick={() => onSelect(bug)} className="min-w-0 text-left">
              <div className="truncate text-xs font-mono text-zinc-400">{fmt(bug.offsetMs)} - {severityLabel(severities, bug.severity)}</div>
            </button>
            {bug.source === 'audio-auto' && (
              <span
                className="shrink-0 whitespace-nowrap rounded px-1.5 py-0.5 text-[10px] font-medium leading-4 bg-sky-950 text-sky-200 ring-1 ring-sky-800"
                title={markerSourceHint(bug)}
              >
                Audio auto
              </span>
            )}
            <div className="ml-auto flex gap-1">
              {allowExport && (
                <button
                  onClick={exportClip}
                  data-testid={`export-${bug.id}`}
                  title={t('bug.exportClip')}
                  className="inline-flex h-8 w-8 items-center justify-center rounded bg-zinc-800 text-zinc-200 hover:bg-blue-700 hover:text-white"
                >
                  <DownloadIcon />
                </button>
              )}
              <button
                onClick={toggleRecording}
                data-testid={`record-audio-${bug.id}`}
                disabled={transcribing}
                title={transcribing ? 'Transcribing speech to note' : recording ? t('bug.stopAudio') : 'Record speech and transcribe into note'}
                className={`inline-flex h-8 w-8 items-center justify-center rounded text-zinc-200 hover:text-white ${
                  recording ? 'bg-red-700 hover:bg-red-600' : transcribing ? 'bg-sky-800 opacity-80' : 'bg-zinc-800 hover:bg-zinc-700'
                }`}
              >
                {transcribing
                  ? <span className="h-4 w-4 animate-spin rounded-full border-2 border-zinc-500 border-t-white" />
                  : <MicIcon />
                }
              </button>
              <button
                onClick={del}
                data-testid={`delete-${bug.id}`}
                title={t('bug.deleteConfirm')}
                className="inline-flex h-8 w-8 items-center justify-center rounded bg-zinc-800 text-zinc-200 hover:bg-red-700 hover:text-white"
              >
                <DeleteIcon />
              </button>
            </div>
          </div>

          <div className="relative">
            <textarea
              ref={noteRef}
              value={note}
              rows={1}
              onChange={(e) => setNote(e.target.value)}
              onFocus={() => setEditingNote(true)}
              onBlur={() => {
                setEditingNote(false)
                void commitNote()
              }}
              onKeyDown={(e) => {
                if (e.key === 'Escape') { setNote(bug.note); (e.target as HTMLTextAreaElement).blur() }
                if (e.key === 'Enter') {
                  e.preventDefault()
                  ;(e.target as HTMLTextAreaElement).blur()
                }
              }}
              maxLength={200}
              placeholder={t('bug.addNote')}
              data-testid={`note-${bug.id}`}
              className="relative min-h-8 w-full resize-none overflow-hidden break-words rounded bg-zinc-950/40 px-2 py-1 text-sm text-zinc-200 outline-none hover:bg-zinc-950 focus:bg-zinc-800 focus:ring-1 focus:ring-blue-600"
            />
          </div>

          <MentionPicker
            options={mentionOptions}
            selectedIds={mentionUserIds}
            aliases={slackAliases}
            dropdownMode="fixed"
            onChange={changeMentions}
          />

          {logcatPreview && (
            <div className="rounded bg-zinc-950/60 px-2 py-1 text-[11px] text-zinc-400" data-testid={`logcat-preview-${bug.id}`} data-row-click-ignore="true">
              <button
                type="button"
                onClick={onToggleLogcat}
                className="mb-1 flex w-full items-center justify-between gap-2 text-left text-zinc-500 hover:text-zinc-300"
              >
                <span>{t('bug.logcatPreview')}</span>
                <span>{logcatExpanded ? t('bug.collapseLogcat') : t('bug.expandLogcat')}</span>
              </button>
              <pre
                className={`overflow-x-auto whitespace-pre-wrap break-words font-mono text-[11px] leading-4 text-zinc-400 ${logcatExpanded ? 'overflow-y-auto' : 'overflow-y-hidden'}`}
                style={{ maxHeight: `${logcatExpanded ? LOGCAT_EXPANDED_LINES : LOGCAT_COLLAPSED_LINES}rem` }}
              >
                {logcatExpanded ? logcatPreview : latestLogcatLines(logcatPreview, LOGCAT_COLLAPSED_LINES)}
              </pre>
            </div>
          )}

          <ClipWindowControl
            id={bug.id}
            pre={pre}
            post={post}
            onPreChange={changePre}
            onPostChange={changePost}
          />
        </div>
      </div>
    </li>
  )
}
